### ISSUE TITLE
Formulario de registro

### ISSUE THREAD

**Issue by Nidev-lab** [Grupo-4-Rolling-Code-45i/Frontend#65]
## Proceso

1. Ingrese a la pagina.
2. Quise registrarme con un nuevo usuario.

## Resultado esperado

• Que no se permitan colocar numero ni signos en donde va el nombre.

## Resultado actual

• Se pueden colocar numero y signos donde va el nombre del usuario.

## Captura

![image](https://github.com/Grupo-4-Rolling-Code-45i/Frontend/assets/53904695/73fadb44-81b3-4316-950a-8357ca4b8dd3)
![image](https://github.com/Grupo-4-Rolling-Code-45i/Frontend/assets/53904695/505dd95c-5efd-4352-8dcc-708818149a5f)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by maximajorel** [comment]
Perfecto nico! Trabajamos en las soluciones y te avisamos

**Comment by maximajorel** [comment]
Revisado Nico! Nos cortas un poco que el hijo de Elon Musk  "Æ A-12" (https://www.bbc.com/mundo/noticias-52566090) nos pida unas pizzas, pero igualmente te hicimos caso 😉
