### ISSUE TITLE
Problemas de responsividad

### ISSUE THREAD

**Issue by Nidev-lab** [Grupo-4-Rolling-Code-45i/Frontend#66]
## Proceso

1. Ingrese a la pagina.
2. Hice responsive en la sección de "contacto".

## Resultado esperado

• Que todo se encuentre correctamente.

## Resultado actual

• El mapa de ubicación se superpone al footer.

## Captura

![image](https://github.com/Grupo-4-Rolling-Code-45i/Frontend/assets/53904695/c897010b-558b-4c9e-bb3b-4fa812fc7d0e)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Nidev-lab** [comment]
Hola chicos buenas! Les dejo cargadas las issues, una vez resueltas las pueden cerrar, esta muy bien logrado el proyecto solo encontré pequeños detalles, quedo a la espera chicos.

**Comment by maximajorel** [comment]
Hola Nico! Perfecto, trabajamos en ellas y te notificamos

**Comment by nicoquinteros23** [comment]
ahora lo vemos

**Comment by maximajorel** [comment]
Revisado!
